# Generated by Django 5.2.6 on 2025-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='position',
            new_name='position_ru',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.AddField(
            model_name='case',
            name='description_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='description_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title_ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name_ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position_ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='text_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='text_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
